name: Deploy RocketCake Site to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload site to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: .  # Adjust if your RocketCake files exist in a subfolder

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
